### ISSUE TITLE
上报的metrics不完整问题

### ISSUE THREAD

**Issue by fxltsbl3855** [toomanyopenfiles/jmxmon#1]
我一个机器上开了两个jmx的java进程（一个端口1099，另一个12345），看日志发现，上报的metrics两个端口不一致。
举例（看截图，截图是jmxmon的一条上报日志，为方便期间，多打了几个回车而已）：
parnew.gc.avg.time 这个metrics只有1099端口有，而12345端口没有；
gc.throughput这个metrics  两个端口都有；

这是为什么？还是存在bug？
![image](https://cloud.githubusercontent.com/assets/8154045/21175848/4c566fe2-c21f-11e6-9b4e-b5f3bb5ae905.png)

**Comment by fxltsbl3855** [comment]
上述问题是不是 每个jvm选择的垃圾收集器不同，所以出现的指标也不同，如果是的话，那就没问题了。

还有一个疑惑就是上述截图中有些指标的value是-1的情况？出现-1是什么原因呢？多谢

**Comment by kiss2008** [comment]
http://blog.csdn.net/xieyuooo/article/details/9817231 这里有一段未经证实的代码，从这里可以看到，GarbageCollector可能出现的名字有
（YGC3种）
java.lang:type=GarbageCollector,name=ParNew
java.lang:type=GarbageCollector,name=Copy
java.lang:type=GarbageCollector,name=PS Scavenge
（FGC3种）
java.lang:type=GarbageCollector,name=ConcurrentMarkSweep
java.lang:type=GarbageCollector,name=MarkSweepCompact
java.lang:type=GarbageCollector,name=PS MarkSweep

关于YGC与FGC的，参考
http://blog.csdn.net/hetaohappy/article/details/53579187?winzoom=1

**Comment by toomanyopenfiles** [comment]
不是bug，正如kiss2008所说，不同进程的gc方式不同，采集信息也会不同。上图中1009端口用的是CMSGC，12345端口用的是PSGC。
